### ISSUE TITLE
Support frame format

### ISSUE THREAD

**Issue by gyscos** [sergey-dryabzhinsky/python-zstd#13]
ZSTD has 2 formats:
- A block format, using `ZSTD_compress` and `ZSTD_decompress`
- A frame format for arbitrary file length

I may have missed it, but I didn't find a way to decompress frame format using this library, or to compress a file into a frame format.

**Comment by sergey-dryabzhinsky** [comment]
Yes, this python wrapper support simpliest block format.

If you mean streaming API - not in current version. May be later.
Or someone help with that.

**Comment by Cyan4973** [comment]
According to : 
https://github.com/indygreg/python-zstandard#comparison-to-other-python-bindings

it seems this python wrapper generates its own compressed format, thanks to a custom header.
The claim looks supported by :
https://github.com/sergey-dryabzhinsky/python-zstd/blob/master/src/python-zstd.c#L88


Note that there is nothing wrong with creating one's own format.
Just, a downside is that files created with a custom header won't be decodable by 3rd party decompressor expecting to read [zstd frame format](https://github.com/facebook/zstd/blob/dev/zstd_compression_format.md).

Reason I'm asking is that, similar to [lz4](http://cyan4973.github.io/lz4/#interoperable-lz4), I wish to list bindings within 2 categories, interoperable and custom format, and I need to list your binding in the correct category.

Regards

**Comment by sergey-dryabzhinsky** [comment]
Hi, @Cyan4973 
Yes, it is. For now this wrapper should be listed as "custom format" and not feature-full.

I'll try to make it more interoperable in near future.

**Comment by sergey-dryabzhinsky** [comment]
@Cyan4973 
As of v1.0.0.99.1 this wrapper uses raw Zstd frame format.
No custom header by default.
And it is still simple - no streaming, no dict support.

**Comment by sergey-dryabzhinsky** [comment]
There is no changes in support of streaming in the future.
I close this.
