### ISSUE TITLE
zstd/lib/compress/zstd_compress.c:55:17: fatal error: mem.h: No such file or directory

### ISSUE THREAD

**Issue by 11zgudu** [sergey-dryabzhinsky/python-zstd#14]
![2016-09-09-181402_883x462_scrot](https://cloud.githubusercontent.com/assets/20792571/18386740/6f9a9fb8-76cb-11e6-9f0b-cf069cef05d4.png)
Please help me! Thanks!

**Comment by 11zgudu** [comment]
pip3, easy_install3 same errors.

**Comment by sergey-dryabzhinsky** [comment]
That's really strange. I see include `-Izstd/lib/common` present in compile command.
Do file `mem.h` exists in `zstd/lib/common` path?

**Comment by sergey-dryabzhinsky** [comment]
Huh? It seems like pypi version is not complete.
I'll try to reload archive.

**Comment by sergey-dryabzhinsky** [comment]
I re-uploaded sources.
Try now with: `pip3 install zstd --no-cache-dir`

**Comment by 11zgudu** [comment]
![2016-09-10-071951_1007x498_scrot](https://cloud.githubusercontent.com/assets/20792571/18405707/045f5f48-7727-11e6-82f2-fdfc864d79b9.png)

**Comment by 11zgudu** [comment]
@sergey-dryabzhinsky A mistake again.

**Comment by sergey-dryabzhinsky** [comment]
I updated sources to 1.0.0.4. Try again.

**Comment by 11zgudu** [comment]
@sergey-dryabzhinsky you pkg zstd-1.0.0.4.tar.gz  "src/python-zstd.h" not in. need add.

**Comment by 11zgudu** [comment]
Otherwise, i'm compile to "zstd.cpython-35m-i386-linux-gnu.so", link /usr/lib/python3.5/lib-dynload/zstd.cpython-35m-i386-linux-gnu.so. 
![2016-09-10-101051_520x141_scrot](https://cloud.githubusercontent.com/assets/20792571/18407303/0dfa0c16-773f-11e6-87e7-54b44602e0d5.png)
What reason?

**Comment by sergey-dryabzhinsky** [comment]
And updated sources again.

I think that Zstd decided that this string is uncompressable.
So result is: length(4b) + header + original string.

I run some tests and found that minimal compressable string is about 25-31 repeated symbol.

**Comment by 11zgudu** [comment]
The problem is solved. I'm download zstd-1.0.0.5.tar.gz (build from source) and pip3 install zstd are Successfully. @sergey-dryabzhinsky
