### ISSUE TITLE
add a open and close (the "with" interface)

### ISSUE THREAD

**Issue by talkaminker** [sergey-dryabzhinsky/python-zstd#15]
gzip has a nice interface for compressing:
like this:

```
    import gzip
    with gzip.open(filename, 'rb') as f:
        return f.read()
```

this is a very nice interface.
can you support it also?

**Comment by sergey-dryabzhinsky** [comment]
My python-zstd bindings are very simple.
It operates only with fixed data blocks, not file handlers.
You can use more advanced bindings from https://github.com/indygreg/python-zstandard

**Comment by sergey-dryabzhinsky** [comment]
And I'll keep it simple.
Sorry.
