### ISSUE TITLE
Zstd 1.4.0.0 installation fails with python version 3.7.3 on WSL

### ISSUE THREAD

**Issue by dorotheeF** [sergey-dryabzhinsky/python-zstd#40]
Installation zstd 1.4.0.0 from WSL, Ubuntu 16.04 fails with python 3.7.3.
By contrast, the installation is successful with the previous python version 3.7.2, WSL and zstd 1.4.0.0.
![2019-05-03_11h00_17](https://user-images.githubusercontent.com/35367216/57128175-df44ed80-6d92-11e9-902d-343bdfc4ec59.png)

**Comment by sergey-dryabzhinsky** [comment]
1. Please provide full install log
2. Try to run `python3.7 setup.py build_ext` in `python-zstd` sources archive

**Comment by dorotheeF** [comment]
More information in attachment. Let me know if you need more.
[log_installation_zstd_WSL_python3.7.3.txt](https://github.com/sergey-dryabzhinsky/python-zstd/files/3141356/log_installation_zstd_WSL_python3.7.3.txt)

**Comment by dorotheeF** [comment]
Result of 2.) in attachment.

[log_execution_zstd_setup.txt](https://github.com/sergey-dryabzhinsky/python-zstd/files/3141416/log_execution_zstd_setup.txt)

**Comment by sergey-dryabzhinsky** [comment]
`fatal error: Python.h: No such file or directory'`
Did you install `python3.7-dev` package?

**Comment by dorotheeF** [comment]
No trace of python3.7-dev installation found. Should I install it ?

**Comment by sergey-dryabzhinsky** [comment]
Yes.

**Comment by dorotheeF** [comment]
Thank you.

**Comment by sergey-dryabzhinsky** [comment]
Did you successfully build python-zstd 1.4.0 on WSL after install of `python3.7-dev`?

**Comment by dorotheeF** [comment]
Yes, after `python3.7-dev` installation,  I was able to install `zstd 1.4.0` with success directly via the command : `pipenv install zstd`.

Thank you for you help.

**Comment by sergey-dryabzhinsky** [comment]
Good.

Closing issue.
