### ISSUE TITLE
How is it different from https://github.com/indygreg/python-zstandard ? Should it be merged with it?

### ISSUE THREAD

**Issue by KOLANICH** [sergey-dryabzhinsky/python-zstd#44]
https://github.com/indygreg/python-zstandard/issues/88

**Comment by sergey-dryabzhinsky** [comment]
Read the LINKS section of README.md

**Comment by KOLANICH** [comment]
> More full-featured and compatible with Zstandard python bindings by Gregory Szorc: https://pypi.python.org/pypi/zstandard

What is the sense to keep this lib rather than use that one then?

**Comment by sergey-dryabzhinsky** [comment]
> These python bindings are kept simple and blunt.
You don't need it - don't use it.
