### ISSUE TITLE
Suggestion for compilation problems

### ISSUE THREAD

**Issue by rodrigobmg** [sergey-dryabzhinsky/python-zstd#58]
Hello,

I noticed an issue when compiling your library using a C compiler. In file python-zstd.c the snippet below will not compile because cctx is not being initialized first. 

`    if (source_size > 0) { //Line 96
        dest = PyBytes_AS_STRING(result);
        ZSTD_CCtx* cctx = ZSTD_createCCtx();`

my warkaround to this is as follow:

`    if (source_size > 0) {
		ZSTD_CCtx* cctx = 0;
        dest = PyBytes_AS_STRING(result);
        cctx = ZSTD_createCCtx();`
        
Thanks for all.

**Comment by sergey-dryabzhinsky** [comment]
Can you provide you system and compiler info?
And how compiler warns about `cctx`?

**Comment by sergey-dryabzhinsky** [comment]
Can't find such errors on my system with gcc-9 / clang-12.

No feedback.
Closing.
