### ISSUE TITLE
Zstd error when running breeze tools of openR

### ISSUE THREAD

**Issue by sgiannoulis** [sergey-dryabzhinsky/python-zstd#59]
Dear, i compiled from source the facebook openr routing protocol as well as the CLI tool breeze that is python based. There is a dependency that zstd module is needed for Breeze to work. So i installed in ubuntu 18.04 using pip3 the zstd library 1.4.8.1 (also tried to install it from source from your git). 
In all cases i get this error when executing the breeze tool:

  File "/usr/local/lib/python3.6/dist-packages/thrift/transport/THeaderTransport.py", line 402, in transform
    buf = zstd.ZstdCompressor(write_content_size=True).compress(buf)
AttributeError: module 'zstd' has no attribute 'ZstdCompressor'

Was there a version of zstd that supported such a method ? Seems FB Thrift lib is trying to access a module of zstd that is no longer there. 
Any insight ?

**Comment by sergey-dryabzhinsky** [comment]
`zstd.ZstdCompressor` never was in there.
You must be used `zstandard` module.

**Comment by sergey-dryabzhinsky** [comment]
No feedback. Close.
