### ISSUE TITLE
What is default level for zstd.compress(data)?

### ISSUE THREAD

**Issue by the-bobo** [sergey-dryabzhinsky/python-zstd#7]
If `zstd.compress(data)` is called without an argument for `level`, what level does it default to? According to python docs for `zlib.compress(string, level)` the default `level` is `6`, and `level` is a range from `0-9`: https://docs.python.org/2/library/zlib.html

You mentioned the range for `level` in `zstd.compress(data, level)` is from `1-20` (https://github.com/sergey-dryabzhinsky/python-zstd/issues/6#issuecomment-228926620). What is its default? I tried checking https://github.com/Cyan4973/zstd but did not find a default.

Thanks.

**Comment by sergey-dryabzhinsky** [comment]
Default level is ```5```.
And maximum level is ```22```.

**Comment by sergey-dryabzhinsky** [comment]
But it is in this module.
In zstd library the default level is ```1```.

**Comment by sergey-dryabzhinsky** [comment]
https://github.com/Cyan4973/zstd/blob/master/lib/compress/zstd_compress.c#L2644

**Comment by the-bobo** [comment]
Thanks, if I understand correctly, the default level for your Python
wrapper around zstd is 5, and the maximum is 22.

Is it possible to train a dictionary from inside a Python script? Yann
mentions using the command line like this:

1) Create the dictionary

zstd --train FullPathToTrainingSet/* -o dictionaryName

2) Compress with dictionary

zstd FILE -D dictionaryName

How can we do that inside a Python script without reading from disk?

1) Can I pass a list of messages to zstd to train a dictionary on?

2) What kind of object is returned as the dictionary?

3) How can I use the dictionary inside my Python program to compress a
string?

Thank you :)

**Comment by sergey-dryabzhinsky** [comment]
No, dictionary not supported by this module by now.
It's in plans but not near future.
