### ISSUE TITLE
OSError: cannot seek zstd decompression stream backwards

### ISSUE THREAD

**Issue by Tcll** [sergey-dryabzhinsky/python-zstd#82]
it seems zstandard `stream_reader` doesn't have a way of buffering a stream for reverse seeking as expected of a file-like object:
```
>>> with open('/pkg/alsa-lib-1.2.6.1-1-x86_64.pkg.tar.zst','rb') as zst:
...     with zstd.stream_reader(zst) as reader:
...         tf = TarFile(fileobj=reader)
...         member = tf.getmember('.PKGINFO')
...         with tf.extractfile(member) as tfmember: content = tfmember.read()
... 
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/usr/lib/python3.10/tarfile.py", line 684, in read
    self.fileobj.seek(offset + (self.position - start))
OSError: cannot seek zstd decompression stream backwards
```
it rather seems to be expected to streamline everything (no pun intended), which is rather unintuitive and dirty:
```
>>> with open('/pkg/alsa-lib-1.2.6.1-1-x86_64.pkg.tar.zst','rb') as zst:
...     with zstd.stream_reader(zst) as reader:
...         tf = TarFile(fileobj=reader)
...         for member in tf:
...             if member.name == '.PKGINFO':
...                 with tf.extractfile(member) as tfobj:
...                     for line in tfobj: line[:-1]
... 
b'# Generated by makepkg 6.0.1'
b'# using fakeroot version 1.26'
b'pkgname = alsa-lib'
b'pkgbase = alsa-lib'
b'pkgver = 1.2.6.1-1'
b'pkgdesc = An alternative implementation of Linux sound support'
b'url = https://www.alsa-project.org'
b'builddate = 1639084234'
b'packager = Artix Build Bot <jenkins@artixlinux.org>'
b'size = 1724949'
b'arch = x86_64'
b'license = LGPL2.1'
b'provides = libasound.so=2-64'
b'provides = libatopology.so=2-64'
b'depend = glibc'
b'depend = alsa-topology-conf'
b'depend = alsa-ucm-conf'
```

unless I'm just doing things the wrong way as opposed to every example my search engine shows me...
if that's the case, could I make a request for handling reverse seeking? :)

**Comment by Tcll** [comment]
update
just stumbled on this issue:
https://github.com/indygreg/python-zstandard/issues/149

not sure if it relates to this project here, however if the intent is shared
could I modify my suggestion to include a `stream_reader(buffering=True)` or `buffered_stream_reader()` specifically for the reverse seek logic that raises the OSError

that way it doesn't alter the existing performance concern by much if at all

**Comment by sergey-dryabzhinsky** [comment]
Not relaeted. Completely.
This project doesn't support stream reading.

**Comment by Tcll** [comment]
I... am such an idiot

I misread the documentation for python-zstandard which had a link to this project
and misunderstood that link to here as this project being related to that documentation

I am so sorry XD
