### ISSUE TITLE
CPython 3.11 wheels on PyPI

### ISSUE THREAD

**Issue by altendky** [sergey-dryabzhinsky/python-zstd#83]
Publishing CPython 3.11 wheels to PyPI would help other projects that use zstd and are working on their own CPython 3.11 support and distribution.

Thanks!

**Comment by sergey-dryabzhinsky** [comment]
I'll hope github actions will work.

**Comment by sergey-dryabzhinsky** [comment]
Well, seems PyPi services have network issues right now.

**Comment by alexmatskevych** [comment]
Hi, is there an update to this issue, since python 3.11 got an official release ?

**Comment by obliviateandsurrender** [comment]
Hey! Any updates on this?

**Comment by altendky** [comment]
Just a friendly check in here.  Looks like you made the minor 3.11 inclusion in https://github.com/sergey-dryabzhinsky/python-zstd/commit/3df52107d797ab1a4e052c119bf3523ff843be8e.  It appears at https://github.com/sergey-dryabzhinsky/python-zstd/compare/v1.5.2.6..master that there hasn't been any interesting changes since the last release, so the extra 3.11 wheels could just be built and uploaded, perhaps.  Am I missing some other work that needs done?  If so, is it something I could help with?

Thanks for your time on this.

**Comment by altendky** [comment]
Just to document the relationship, with https://github.com/sergey-dryabzhinsky/python-zstd/pull/84 merged there are two artifact groups to be added.  (and thanks!)

**Comment by sergey-dryabzhinsky** [comment]
Done with 1.5.4.0 release

**Comment by altendky** [comment]
Thanks!
