### ISSUE TITLE
zstd.Error: Bad threads count - more than 200: 240

### ISSUE THREAD

**Issue by zplizzi** [sergey-dryabzhinsky/python-zstd#92]
It seems like `zstd.compress(data, level)` will fail on a system that has too many cores. My system has 2 64-core CPUs and with 2 threads per, that's 256 virtual cores. 

This is especially annoying since the usage of zstd is buried deep in another library so I can't easily pass a threads flag. And `ZSTD_NBTHREADS` isn't seeming to do anything.

This problem is also mentioned here: https://github.com/Chia-Network/chia-blockchain/issues/14667

**Comment by zplizzi** [comment]
I don't know the details of zstd, but i think as long as that wouldn't cause problems that seems fine. Or if there's diminishing returns / downsides to having too many threads, something like `min(16, system_max_threads)` could be fine too.

**Comment by zplizzi** [comment]
I think a warning is only necessary if taking the default would cause problems. The user can choose to specify the number of threads if they need more control.

**Comment by sergey-dryabzhinsky** [comment]
Try latest release 1.5.4.1

**Comment by zplizzi** [comment]
Thank you, that does seem to fix the issue! Much appreciated :)
