### ISSUE TITLE
zstd.Error: Decompression error: Destination buffer is too small

### ISSUE THREAD

**Issue by DavidBuchanan314** [sergey-dryabzhinsky/python-zstd#94]
I'm learning about the zstd format, and I crafted a simple "hello world" file. It consists of two Frames, each containing one Raw (uncompressed) Block of data. The first contains "hello\n", the second, "world\n". As far as I can tell, my file is valid, and it can be extracted successfully using the `zstd` command-line too, however the python library fails with the error: `zstd.Error: Decompression error: Destination buffer is too small`.

See below:

```python
import zstd
import os

data = bytes.fromhex("28b52ffd200631000068656c6c6f0a28b52ffd2006310000776f726c640a")

with open("test.zst", "wb") as f:
	f.write(data)

os.system("zstd -cd test.zst")  # works, prints "hello\nworld\n"

print(zstd.decompress(data))  # zstd.Error: Decompression error: Destination buffer is too small
```

**Comment by DavidBuchanan314** [comment]
Per the zstd spec:

> The decompressed content of multiple concatenated frames is the concatenation of each frame decompressed content.

**Comment by sergey-dryabzhinsky** [comment]
Done in 1.5.5.1

**Comment by wuxianseng** [comment]
zstd-jni-1.5.4-1.jar exists bug？com.github.luben.zstd.ZstdException: Destination buffer is too small

**Comment by wuxianseng** [comment]
![image](https://github.com/sergey-dryabzhinsky/python-zstd/assets/29628381/7504f389-e6c5-40b2-9396-b08eb920ef96)

**Comment by DavidBuchanan314** [comment]
@wuxianseng you appear to be using https://github.com/luben/zstd-jni, not https://github.com/sergey-dryabzhinsky/python-zstd, on the basis that your code is java and not python, and your screenshot contains the name of the java library in question
